#!/usr/bin/env python3
"""Regenerate src/fsdata_custom.c from the html/ directory.

Produces the lwIP makefsdata format (the same layout the ST example used),
with each file's name + HTTP header + content in one byte array, and the
fsdata_file entries linked together.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
HTML = os.path.join(HERE, "html")
OUT = os.path.join(HERE, "src", "fsdata_custom.c")

# Serving order: first entry is FS_ROOT.
FILES = ["index.html", "led.shtml", "status.shtml", "404.html"]

HEADER = (
    "HTTP/1.0 200 OK\r\n"
    "Server: lwIP/1.3.1 (http://savannah.nongnu.org/projects/lwip)\r\n"
    "Content-type: text/html\r\n"
    "Expires: Fri, 10 Apr 2008 14:00:00 GMT\r\n"
    "Pragma: no-cache\r\n"
    "\r\n"
)


def cname(n):
    return n.replace(".", "_").replace("/", "_")


def hex_lines(b, width=16):
    out = []
    for i in range(0, len(b), width):
        chunk = b[i : i + width]
        out.append("  " + ",".join("0x%02x" % x for x in chunk) + ",")
    return "\n".join(out)


def main():
    files = []          # (cname, bytearray(name+null+header+content), offset)
    for name in FILES:
        path = os.path.join(HTML, name)
        with open(path, "rb") as f:
            content = f.read()
        fname = "/" + name                       # lwIP fs uses "/file" names
        blob = fname.encode() + b"\x00" + HEADER.encode() + content
        files.append((cname(name), blob, len(fname) + 1))

    out = []
    out.append("/* fsdata_custom.c - generated by make_fsdata.py. Do not edit. */")
    out.append('#include "lwip/apps/fs.h"')
    out.append('#include "lwip/def.h"')
    out.append('#include "fsdata.h"')
    out.append("")
    out.append("#define file_NULL (struct fsdata_file *) NULL")
    out.append("")

    for cn, blob, offset in files:
        align = 5 if cn.endswith("shtml") else 4
        out.append("static const unsigned int dummy_align__%s = %d;" % (cn, align))
        out.append("static const unsigned char data__%s[] = {" % cn)
        out.append("/* /%s (%d chars) */" % (cn.replace("_", "."), len(blob)))
        out.append(hex_lines(blob))
        out.append("};")
        out.append("")

    # Emit the fsdata_file entries in REVERSE order so that each entry can
    # reference the next one (already defined) as its "next" pointer.
    for i in range(len(files) - 1, -1, -1):
        cn, blob, offset = files[i]
        nxt = "file_NULL" if i == len(files) - 1 else "file__%s" % files[i + 1][0]
        out.append("const struct fsdata_file file__%s[] = { {" % cn)
        out.append("%s," % nxt)
        out.append("data__%s," % cn)
        out.append("data__%s + %d," % (cn, offset))
        out.append("sizeof(data__%s) - %d," % (cn, offset))
        out.append("1,")
        out.append("}};")
        out.append("")

    out.append("#define FS_ROOT file__%s" % files[0][0])
    out.append("#define FS_NUMFILES %d" % len(files))
    out.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print("wrote %s (%d files)" % (OUT, len(files)))


if __name__ == "__main__":
    main()
