#!/usr/bin/env python3
"""Build the MX25L51245G probe-rs flash algorithm and generate a target YAML.

Compiles flash_mx25l512_qspi.c (position-independent, 1-line SPI mode) with
arm-none-eabi-gcc, extracts the code blob + entry-point offsets, and writes
target_mx25l512_qspi.yaml for use with:

  probe-rs download --chip-description-path target_mx25l512_qspi.yaml \
      --chip STM32F769NI-MX25L51245G-mx25l512_qspi --binary-format hex app.hex
"""
import base64
import subprocess
import sys
import os

HERE = os.path.dirname(os.path.abspath(__file__))
GCC = r"D:/Arm/GNU Toolchain mingw-w64-x86_64-arm-none-eabi/bin/arm-none-eabi-gcc.exe"
LD = r"D:/Arm/GNU Toolchain mingw-w64-x86_64-arm-none-eabi/bin/arm-none-eabi-ld.exe"
NM = r"D:/Arm/GNU Toolchain mingw-w64-x86_64-arm-none-eabi/bin/arm-none-eabi-nm.exe"
OBJCOPY = r"D:/Arm/GNU Toolchain mingw-w64-x86_64-arm-none-eabi/bin/arm-none-eabi-objcopy.exe"

LOAD = 0x20000000       # link base (algo.ld) - offsets are relative to this
RUNTIME_LOAD = 0x20000020  # runtime load point (probe-rs prepends a 4-byte BKPT header before it)

CHIP = "STM32F769NI"
FLASH_LO = 0x90000000   # QSPI memory-mapped base
FLASH_HI = 0x94000000   # MX25L51245G = 64 MB
RAM_LO   = 0x20000000   # DTCM
RAM_HI   = 0x20020000   # 128 KB


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"command failed: {' '.join(cmd)}\n{r.stderr}")
    return r.stdout


def main() -> int:
    src = sys.argv[1] if len(sys.argv) > 1 else "flash_mx25l512_qspi.c"
    stem = os.path.splitext(os.path.basename(src))[0]
    base = stem[6:] if stem.startswith("flash_") else stem   # flash_xxx -> xxx
    page_size = sys.argv[2] if len(sys.argv) > 2 else "0x1000"
    run([GCC, "-mcpu=cortex-m7", "-mthumb", "-mfloat-abi=soft",
         "-ffreestanding", "-fno-builtin", "-fno-stack-protector",
         "-fomit-frame-pointer", "-O2", "-Wall", "-c",
         src, "-o", "flash.o"])
    run([LD, "-T", "algo.ld", "flash.o", "-o", "flash.elf"])
    run([OBJCOPY, "-O", "binary", "flash.elf", "flash.bin"])

    blob = open(os.path.join(HERE, "flash.bin"), "rb").read()
    b64 = base64.b64encode(blob).decode()

    # symbol -> offset (from the linked base 0x20000000)
    nm = run([NM, "-n", "flash.elf"])
    sym = {}
    for line in nm.splitlines():
        parts = line.split()
        if len(parts) == 3:
            addr, _typ, name = int(parts[0], 16), parts[1], parts[2]
            sym[name] = addr - LOAD

    for fn in ("Init", "UnInit", "EraseSector", "EraseChip", "ProgramPage", "Verify"):
        if fn not in sym:
            sys.exit(f"symbol {fn} not found")

    yaml = f"""# Auto-generated by build_algo.py - MX25L51245G flash algorithm ({base}).
name: {CHIP} MX25L51245G {base}
variants:
  - name: {CHIP}-MX25L51245G-{base}
    package_variants:
      - STM32F769NIHx
    cores:
      - name: main
        type: armv7em
        core_access_options: !Arm
          ap: !v1 0
    memory_map:
      - !Ram
        name: DTCM
        range:
          start: 0x{RAM_LO:x}
          end: 0x{RAM_HI:x}
        cores:
          - main
      - !Nvm
        name: MX25L51245G
        range:
          start: 0x{FLASH_LO:x}
          end: 0x{FLASH_HI:x}
        cores:
          - main
        access:
          write: false
          boot: true
    flash_algorithms:
      - mx25l512_stm32f769
flash_algorithms:
  - name: mx25l512_stm32f769
    description: MX25L51245G 64MB via STM32F769NI ({base})
    default: true
    instructions: {b64}
    load_address: 0x{RUNTIME_LOAD:x}
    pc_init: 0x{sym['Init']:x}
    pc_uninit: 0x{sym['UnInit']:x}
    pc_program_page: 0x{sym['ProgramPage']:x}
    pc_erase_sector: 0x{sym['EraseSector']:x}
    pc_erase_all: 0x{sym['EraseChip']:x}
    pc_verify: 0x{sym['Verify']:x}
    data_section_offset: 0x0
    stack_size: 0x400
    flash_properties:
      address_range:
        start: 0x{FLASH_LO:x}
        end: 0x{FLASH_HI:x}
      page_size: {page_size}
      erased_byte_value: 0xff
      program_page_timeout: 500
      erase_sector_timeout: 1000
      sectors:
        - size: 0x1000
          address: 0x0
"""
    out = os.path.join(HERE, f"target_{base}.yaml")
    with open(out, "w") as f:
        f.write(yaml)
    print(f"wrote {out} (blob {len(blob)} bytes)")
    for fn in ("Init", "UnInit", "EraseSector", "EraseChip", "ProgramPage", "Verify"):
        print(f"  {fn} @ 0x{sym[fn]:x}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
