/**
  * @file    eth_http/src/http_server.c
  * @brief   lwIP raw-API HTTP server for the bundled single-page site.
  *
  * Serves the single-page app (gzip, CSS/JS inlined, from Inc/web_assets.h,
  * generated by e_server/build_web.py from e_server/web/ + e_server/public/)
  * plus the JSON API:
  *
  *   GET  /                 page, Content-Encoding: gzip
  *   GET  /api/leds         {"leds":[0,1,0]}       (real LED GPIO state)
  *   POST /api/leds         body {"leds":[0,1,0]}  -> applies to the LEDs
  *   GET  /api/adc          {"vrefint_mv":..,"temp_c":..,"vbat_v":..,"ts":..}
  *   GET  /api/info         {"arch","lan_ip","public_ip":null,"geo":null,
  *                           "weather":null}
  *   GET  /public/<name>    raw image bytes (from the embedded_files[] table)
  *
  * The public IP / geo / weather fields are reported as null (the page shows
  * "N/A") because the board has no HTTP/TLS client; see the README for what
  * an HTTPS client would require.
  *
  * Responses are paced through tcp_sent: static bodies (page/images) are
  * written from flash without copying, JSON is built into the per-connection
  * buffer. NO_SYS / raw API - all callbacks run in the main loop while
  * ethernetif_input() is polled.
  */

#include "stm32f7xx_hal.h"
#include "lwip/opt.h"
#include "lwip/tcp.h"
#include "lwip/mem.h"
#include "lwip/ip_addr.h"
#include "lwip/netif.h"
#include "http_server.h"
#include "web_assets.h"
#include "main.h"

#include <stdio.h>
#include <string.h>

extern struct netif gnetif;

/* --------------------------------------------------------------------------
 * On-board LEDs (LD1 PJ13, LD2 PJ5, LD3 PA12 - all high active).
 * ------------------------------------------------------------------------ */
#define LED_PORT_LD1  GPIOJ
#define LED_PIN_LD1   GPIO_PIN_13
#define LED_PORT_LD2  GPIOJ
#define LED_PIN_LD2   GPIO_PIN_5
#define LED_PORT_LD3  GPIOA
#define LED_PIN_LD3   GPIO_PIN_12

static void leds_init(void)
{
  GPIO_InitTypeDef gpio = {0};

  __HAL_RCC_GPIOJ_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();

  gpio.Mode  = GPIO_MODE_OUTPUT_PP;
  gpio.Pull  = GPIO_NOPULL;
  gpio.Speed = GPIO_SPEED_FREQ_LOW;
  gpio.Pin   = LED_PIN_LD1;
  HAL_GPIO_Init(LED_PORT_LD1, &gpio);
  gpio.Pin   = LED_PIN_LD2;
  HAL_GPIO_Init(LED_PORT_LD2, &gpio);
  gpio.Pin   = LED_PIN_LD3;
  HAL_GPIO_Init(LED_PORT_LD3, &gpio);
}

static int led_get(int i)
{
  GPIO_TypeDef *port;
  uint16_t pin;
  switch (i)
  {
    case 0: port = LED_PORT_LD1; pin = LED_PIN_LD1; break;
    case 1: port = LED_PORT_LD2; pin = LED_PIN_LD2; break;
    default: port = LED_PORT_LD3; pin = LED_PIN_LD3; break;
  }
  return HAL_GPIO_ReadPin(port, pin) == GPIO_PIN_SET;
}

static void led_set(int i, int on)
{
  GPIO_TypeDef *port;
  uint16_t pin;
  switch (i)
  {
    case 0: port = LED_PORT_LD1; pin = LED_PIN_LD1; break;
    case 1: port = LED_PORT_LD2; pin = LED_PIN_LD2; break;
    default: port = LED_PORT_LD3; pin = LED_PIN_LD3; break;
  }
  HAL_GPIO_WritePin(port, pin, on ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/* --------------------------------------------------------------------------
 * Internal ADC channels (die temperature / VREFINT / VBAT), the same
 * measurement as the old status page and blink_hello.
 * ------------------------------------------------------------------------ */
#define ADC_CAL_VREF_MV  3300U
#define ADC_MAX_VALUE    4095U

static ADC_HandleTypeDef hadc1;
static uint8_t adc_ready;

static void adc_init(void)
{
  __HAL_RCC_ADC1_CLK_ENABLE();

  hadc1.Instance = ADC1;
  hadc1.Init.ClockPrescaler        = ADC_CLOCKPRESCALER_PCLK_DIV4;
  hadc1.Init.Resolution            = ADC_RESOLUTION_12B;
  hadc1.Init.ScanConvMode          = DISABLE;
  hadc1.Init.ContinuousConvMode    = DISABLE;
  hadc1.Init.DiscontinuousConvMode = DISABLE;
  hadc1.Init.NbrOfDiscConversion   = 0;
  hadc1.Init.ExternalTrigConvEdge  = ADC_EXTERNALTRIGCONVEDGE_NONE;
  hadc1.Init.ExternalTrigConv      = ADC_EXTERNALTRIGCONV_T1_CC1;
  hadc1.Init.DataAlign             = ADC_DATAALIGN_RIGHT;
  hadc1.Init.NbrOfConversion       = 1;
  hadc1.Init.DMAContinuousRequests = DISABLE;
  hadc1.Init.EOCSelection          = DISABLE;
  HAL_ADC_Init(&hadc1);
}

static uint32_t adc_read_channel(uint32_t channel, uint32_t sampling_time)
{
  ADC_ChannelConfTypeDef sConfig = {0};
  uint32_t value = 0;

  sConfig.Channel      = channel;
  sConfig.Rank         = 1;
  sConfig.SamplingTime = sampling_time;
  sConfig.Offset       = 0;
  HAL_ADC_ConfigChannel(&hadc1, &sConfig);

  if (channel == ADC_CHANNEL_VBAT)
  {
    HAL_Delay(1);   /* VBATE settle before the first sample */
  }

  HAL_ADC_Start(&hadc1);
  if (HAL_ADC_PollForConversion(&hadc1, 100) == HAL_OK)
  {
    value = HAL_ADC_GetValue(&hadc1);
  }
  HAL_ADC_Stop(&hadc1);

  return value;
}

static void adc_measure(float *vdda_mv, float *temp_c, float *vbat_v)
{
  uint32_t vrefint_raw, ts_raw, vbat_raw;
  uint16_t vrefint_cal, ts_cal1, ts_cal2;

  if (!adc_ready)
  {
    adc_init();
    adc_ready = 1;
  }

  vrefint_raw = adc_read_channel(ADC_CHANNEL_VREFINT, ADC_SAMPLETIME_480CYCLES);
  ts_raw      = adc_read_channel(ADC_CHANNEL_TEMPSENSOR, ADC_SAMPLETIME_480CYCLES);
  vbat_raw    = adc_read_channel(ADC_CHANNEL_VBAT, ADC_SAMPLETIME_480CYCLES);

  vrefint_cal = *((uint16_t *)0x1FF0F44AU);   /* VREFINT_CAL */
  ts_cal1     = *((uint16_t *)0x1FF0F44CU);   /* TS_CAL1, 30 degC */
  ts_cal2     = *((uint16_t *)0x1FF0F44EU);   /* TS_CAL2, 110 degC */

  *vdda_mv = (float)ADC_CAL_VREF_MV * (float)vrefint_cal / (float)vrefint_raw;
  *temp_c  = 30.0f + ((float)ts_raw * (float)vrefint_cal / (float)vrefint_raw
                      - (float)ts_cal1) * (110.0f - 30.0f)
                      / ((float)ts_cal2 - (float)ts_cal1);
  /* VBAT is returned in volts to match the front-end plot scale. */
  *vbat_v  = 4.0f * (float)vbat_raw * *vdda_mv / (float)ADC_MAX_VALUE / 1000.0f;
}

/* --------------------------------------------------------------------------
 * TCP connection state + response pacing.
 * ------------------------------------------------------------------------ */
#define HTTP_RX_BUF   1024
#define HTTP_RESP_BUF 512

struct http_conn
{
  struct tcp_pcb *pcb;
  char rx[HTTP_RX_BUF];          /* accumulated request */
  size_t rx_len;
  char resp[HTTP_RESP_BUF];      /* header (+ JSON body) */
  size_t hdr_len;
  const uint8_t *body_ptr;       /* static body (page / image) or NULL */
  size_t body_len;
  u8_t body_static;              /* body_ptr points into const flash */
  size_t total_off;              /* bytes of response queued to lwIP */
  u8_t done;                     /* whole response queued */
};

static err_t http_recv(void *arg, struct tcp_pcb *pcb, struct pbuf *p, err_t err);
static err_t http_sent(void *arg, struct tcp_pcb *pcb, u16_t len);
static void  http_err(void *arg, err_t err);

/* Queue as much of the response as fits; the rest is sent from tcp_sent. */
static void conn_send(struct http_conn *c)
{
  for (;;)
  {
    const uint8_t *ptr;
    size_t left;
    u8_t flags;

    if (c->total_off < c->hdr_len)
    {
      ptr   = (const uint8_t *)c->resp + c->total_off;
      left  = c->hdr_len - c->total_off;
      flags = TCP_WRITE_FLAG_COPY;   /* header is in the per-conn buffer */
    }
    else
    {
      size_t bo = c->total_off - c->hdr_len;
      if (bo >= c->body_len)
      {
        c->done = 1;
        break;
      }
      ptr   = c->body_ptr + bo;
      left  = c->body_len - bo;
      flags = c->body_static ? 0 : TCP_WRITE_FLAG_COPY;
    }

    {
      u16_t chunk = (u16_t)LWIP_MIN(left, 2048);
      if (tcp_write(c->pcb, ptr, chunk, flags) != ERR_OK) break;
      c->total_off += chunk;
    }
  }
  tcp_output(c->pcb);
}

/* Close and free the connection once the response is fully queued. */
static void http_conn_close(struct http_conn *c)
{
  err_t err = tcp_close(c->pcb);
  if (err == ERR_OK)
  {
    tcp_arg(c->pcb, NULL);
    tcp_recv(c->pcb, NULL);
    tcp_sent(c->pcb, NULL);
    tcp_err(c->pcb, NULL);
    mem_free(c);
  }
  /* else: retried from tcp_sent when the send buffer drains */
}

static void http_reply_json(struct http_conn *c, const char *body)
{
  int n = snprintf(c->resp, sizeof(c->resp),
                   "HTTP/1.1 200 OK\r\n"
                   "Content-Type: application/json; charset=utf-8\r\n"
                   "Content-Length: %u\r\n"
                   "Cache-Control: no-store\r\n"
                   "Connection: close\r\n"
                   "\r\n"
                   "%s",
                   (unsigned)strlen(body), body);
  c->hdr_len = (size_t)n;
  c->body_ptr = NULL;
  c->body_len = 0;
  c->body_static = 0;
  c->total_off = 0;
  c->done = 0;
  conn_send(c);
  if (c->done) http_conn_close(c);
}

static void http_reply_err(struct http_conn *c, int code, const char *status)
{
  int n = snprintf(c->resp, sizeof(c->resp),
                   "HTTP/1.1 %d %s\r\n"
                   "Content-Type: text/plain\r\n"
                   "Content-Length: 0\r\n"
                   "Cache-Control: no-store\r\n"
                   "Connection: close\r\n"
                   "\r\n",
                   code, status);
  c->hdr_len = (size_t)n;
  c->body_ptr = NULL;
  c->body_len = 0;
  c->body_static = 0;
  c->total_off = 0;
  c->done = 0;
  conn_send(c);
  if (c->done) http_conn_close(c);
}

static void http_reply_static(struct http_conn *c, const char *ctype,
                              const char *encoding,
                              const uint8_t *data, size_t len)
{
  int n = snprintf(c->resp, sizeof(c->resp),
                   "HTTP/1.1 200 OK\r\n"
                   "Content-Type: %s\r\n"
                   "%s"
                   "Content-Length: %lu\r\n"
                   "Cache-Control: no-store\r\n"
                   "Connection: close\r\n"
                   "\r\n",
                   ctype,
                   encoding ? encoding : "",
                   (unsigned long)len);
  c->hdr_len = (size_t)n;
  c->body_ptr = data;
  c->body_len = len;
  c->body_static = 1;
  c->total_off = 0;
  c->done = 0;
  conn_send(c);
  if (c->done) http_conn_close(c);
}

/* --------------------------------------------------------------------------
 * API handlers.
 * ------------------------------------------------------------------------ */
static void api_leds(struct http_conn *c, const char *method, const char *body)
{
  if (strcmp(method, "POST") == 0 && body)
  {
    const char *b = strchr(body, '[');
    if (b)
    {
      int a[3] = { 0, 0, 0 };
      int got = sscanf(b + 1, "%d , %d , %d", &a[0], &a[1], &a[2]);
      for (int i = 0; i < got && i < 3; i++) led_set(i, a[i] ? 1 : 0);
    }
  }

  char resp[64];
  int n = snprintf(resp, sizeof(resp), "{\"leds\":[%d,%d,%d]}",
                   led_get(0), led_get(1), led_get(2));
  http_reply_json(c, resp);
}

static void api_adc(struct http_conn *c)
{
  float vdda_mv, temp_c, vbat_v;
  char body[160];

  adc_measure(&vdda_mv, &temp_c, &vbat_v);
  int n = snprintf(body, sizeof(body),
                   "{\"vrefint_mv\":%.1f,\"temp_c\":%.1f,\"vbat_v\":%.2f,\"ts\":%lu}",
                   vdda_mv, temp_c, vbat_v, (unsigned long)HAL_GetTick());
  http_reply_json(c, body);
}

static void api_info(struct http_conn *c)
{
  char body[512];
  char lan[16];

  ip4addr_ntoa_r(netif_ip4_addr(&gnetif), lan, sizeof(lan));
  int n = snprintf(body, sizeof(body),
                   "{\"arch\":\"cortex-m7\",\"lan_ip\":\"%s\",\"public_ip\":null,"
                   "\"geo\":null,\"weather\":null,\"ts\":%lu}",
                   lan, (unsigned long)HAL_GetTick());
  http_reply_json(c, body);
}

static void serve_public(struct http_conn *c, const char *path)
{
  for (unsigned i = 0; i < embedded_files_count; i++)
  {
    if (strcmp(path, embedded_files[i].path) == 0)
    {
      http_reply_static(c, embedded_files[i].ctype, NULL,
                        embedded_files[i].data, embedded_files[i].len);
      return;
    }
  }
  http_reply_err(c, 404, "Not Found");
}

static void process_request(struct http_conn *c)
{
  char method[8], path[1024];
  const char *body;

  if (sscanf(c->rx, "%7s %1023s", method, path) != 2)
  {
    http_reply_err(c, 400, "Bad Request");
    return;
  }
  {
    char *q = strchr(path, '?');
    if (q) *q = 0;
  }
  body = strstr(c->rx, "\r\n\r\n");
  body = body ? body + 4 : NULL;

  if (strcmp(path, "/") == 0 || strcmp(path, "/index.html") == 0)
  {
    http_reply_static(c, "text/html; charset=utf-8",
                      "Content-Encoding: gzip\r\n",
                      index_html_gz, index_html_gz_len);
  }
  else if (strcmp(path, "/api/leds") == 0)
  {
    api_leds(c, method, body);
  }
  else if (strcmp(path, "/api/adc") == 0)
  {
    api_adc(c);
  }
  else if (strcmp(path, "/api/info") == 0)
  {
    api_info(c);
  }
  else if (strcmp(path, "/favicon.ico") == 0)
  {
    http_reply_err(c, 204, "No Content");
  }
  else if (strncmp(path, "/public/", 8) == 0)
  {
    serve_public(c, path);
  }
  else
  {
    http_reply_err(c, 404, "Not Found");
  }
}

/* --------------------------------------------------------------------------
 * lwIP raw TCP callbacks.
 * ------------------------------------------------------------------------ */
static err_t http_recv(void *arg, struct tcp_pcb *pcb, struct pbuf *p, err_t err)
{
  struct http_conn *c = arg;

  if (err != ERR_OK) return ERR_OK;

  if (p == NULL)
  {
    if (c) { c->done = 1; http_conn_close(c); }
    return ERR_OK;
  }

  if (c)
  {
    if (c->rx_len + p->tot_len < sizeof(c->rx))
    {
      pbuf_copy_partial(p, c->rx + c->rx_len, p->tot_len, 0);
      c->rx_len += p->tot_len;
    }
    tcp_recved(pcb, p->tot_len);

    c->rx[c->rx_len] = 0;
    {
      char *hdr_end = strstr(c->rx, "\r\n\r\n");
      if (hdr_end)
      {
        long cl = 0;
        const char *clh = strstr(c->rx, "Content-Length:");
        if (clh)
        {
          clh += 15;
          while (*clh == ' ') clh++;
          cl = atol(clh);
        }
        {
          size_t want = (size_t)(hdr_end - c->rx) + 4 + (size_t)cl;
          if (c->rx_len >= want)
          {
            c->rx[want] = 0;
            process_request(c);
          }
        }
      }
    }
  }
  pbuf_free(p);
  return ERR_OK;
}

static err_t http_sent(void *arg, struct tcp_pcb *pcb, u16_t len)
{
  struct http_conn *c = arg;
  LWIP_UNUSED_ARG(pcb);
  LWIP_UNUSED_ARG(len);

  if (!c) return ERR_OK;
  if (c->done)
  {
    http_conn_close(c);
  }
  else
  {
    conn_send(c);
  }
  return ERR_OK;
}

static void http_err(void *arg, err_t err)
{
  struct http_conn *c = arg;
  LWIP_UNUSED_ARG(err);
  if (c) mem_free(c);
}

static err_t http_accept(void *arg, struct tcp_pcb *newpcb, err_t err)
{
  struct http_conn *c;
  LWIP_UNUSED_ARG(arg);

  if (err != ERR_OK || newpcb == NULL) return ERR_VAL;

  c = (struct http_conn *)mem_malloc(sizeof(*c));
  if (!c) return ERR_MEM;
  memset(c, 0, sizeof(*c));
  c->pcb = newpcb;

  tcp_arg(newpcb, c);
  tcp_recv(newpcb, http_recv);
  tcp_sent(newpcb, http_sent);
  tcp_err(newpcb, http_err);
  return ERR_OK;
}

/* --------------------------------------------------------------------------
 * Server entry point.
 * ------------------------------------------------------------------------ */
void http_server_init(void)
{
  struct tcp_pcb *pcb;

  leds_init();
  led_set(0, 0);
  led_set(1, 0);
  led_set(2, 0);

  pcb = tcp_new();
  if (!pcb) return;
  if (tcp_bind(pcb, IP_ADDR_ANY, 80) != ERR_OK) return;
  pcb = tcp_listen(pcb);
  if (!pcb) return;
  tcp_accept(pcb, http_accept);
}
