/**
 * @file    server.c
 * @brief   e_server reference C backend (host-side).
 *
 * A minimal single-page web server that mirrors the API the STM32F769I
 * board's embedded server will implement. It serves the gzipped, CSS/JS
 * inlined page (from web_assets.h, generated by build_web.py) and three JSON
 * endpoints:
 *
 *   GET  /             gzip page (Content-Encoding: gzip)
 *   GET  /api/leds     {"leds":[0,1,0]}
 *   POST /api/leds     body {"leds":[0,1,0]} -> applied, {"leds":[0,1,0]}
 *   GET  /api/adc      {"vrefint_mv":..,"temp_c":..,"vbat_v":..,"ts":..}
 *   GET  /api/info     {"arch","lan_ip","public_ip","geo","weather","ts"}
 *   GET  /public/<name>  raw image bytes (from the embedded_files[] table)
 *
 * The /api/info external lookups (public IP via api.ipify.org, geo via
 * ip-api.com, weather via wttr.in) are best-effort plain-HTTP fetches; any
 * failure yields JSON nulls and the page shows "N/A". On the board these
 * would be implemented with an HTTP client (+TLS for HTTPS upstreams).
 *
 * Build:  python build_web.py && gcc -O2 -o e_server server.c
 *         (Windows/MinGW adds -lws2_32)
 * Run:    ./e_server [port]      default 8080
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <time.h>
#include <math.h>

#include "web_assets.h"

/* --------------------------------------------------------------------------
 * Platform socket layer (Winsock vs POSIX).
 * ------------------------------------------------------------------------ */
#if defined(_WIN32)
  #include <winsock2.h>
  #include <ws2tcpip.h>
  #include <process.h>
  #include <windows.h>
  typedef SOCKET sock_t;
  #define INVALID_SOCK INVALID_SOCKET
  #define XCLOSE(s) closesocket(s)
  #define SOCK_ERR SOCKET_ERROR
  static void sock_init(void) { WSADATA w; WSAStartup(MAKEWORD(2, 2), &w); }
  #define THREAD_RET unsigned __stdcall
  typedef HANDLE thread_t;
#else
  #include <sys/types.h>
  #include <sys/socket.h>
  #include <netinet/in.h>
  #include <arpa/inet.h>
  #include <netdb.h>
  #include <unistd.h>
  #include <pthread.h>
  #include <signal.h>
  #include <sys/time.h>
  typedef int sock_t;
  #define INVALID_SOCK (-1)
  #define XCLOSE(s) close(s)
  #define SOCK_ERR (-1)
  static void sock_init(void) { signal(SIGPIPE, SIG_IGN); }
  #define THREAD_RET void *
  typedef pthread_t thread_t;
#endif

/* --------------------------------------------------------------------------
 * Helpers
 * ------------------------------------------------------------------------ */
static char *xstrdup(const char *s)
{
  size_t n = strlen(s) + 1;
  char *p = malloc(n);
  if (p) memcpy(p, s, n);
  return p;
}

static void send_all(sock_t fd, const void *buf, size_t len)
{
  const char *p = buf;
  while (len > 0)
  {
    int n = send(fd, p, (int)len, 0);
    if (n <= 0) return;
    p += n;
    len -= (size_t)n;
  }
}

static void set_recv_timeout(sock_t s, int ms)
{
#if defined(_WIN32)
  DWORD t = (DWORD)ms;
  setsockopt(s, SOL_SOCKET, SO_RCVTIMEO, (const char *)&t, sizeof(t));
#else
  struct timeval tv;
  tv.tv_sec = ms / 1000;
  tv.tv_usec = (ms % 1000) * 1000;
  setsockopt(s, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
#endif
}

static sock_t tcp_connect(const char *host, int port, int timeout_ms)
{
  struct addrinfo hints, *res = NULL, *rp;
  char port_s[8];
  sock_t s = INVALID_SOCK;

  snprintf(port_s, sizeof(port_s), "%d", port);
  memset(&hints, 0, sizeof(hints));
  hints.ai_family = AF_INET;
  hints.ai_socktype = SOCK_STREAM;
  if (getaddrinfo(host, port_s, &hints, &res) != 0) return INVALID_SOCK;

  for (rp = res; rp; rp = rp->ai_next)
  {
    s = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);
    if (s == INVALID_SOCK) continue;
    if (connect(s, rp->ai_addr, (int)rp->ai_addrlen) == 0) break;
    XCLOSE(s);
    s = INVALID_SOCK;
  }
  freeaddrinfo(res);
  if (s != INVALID_SOCK) set_recv_timeout(s, timeout_ms);
  return s;
}

static char *read_all(sock_t fd)
{
  size_t cap = 8192, got = 0;
  char *b = malloc(cap);
  if (!b) return NULL;
  for (;;)
  {
    if (got + 4096 > cap)
    {
      cap *= 2;
      char *nb = realloc(b, cap);
      if (!nb) break;
      b = nb;
    }
    int r = recv(fd, b + got, 4096, 0);
    if (r <= 0) break;
    got += (size_t)r;
  }
  b[got] = 0;
  return b;
}

/* --------------------------------------------------------------------------
 * Minimal plain-HTTP client (for the /api/info external lookups).
 * Follows one http->http redirect. Returns the response body or NULL.
 * ------------------------------------------------------------------------ */
static char *http_get(const char *host, int port, const char *path)
{
  char nh[256], np[512];      /* survive across redirect iterations */
  int redirected = 0;

  for (int attempt = 0; attempt < 3; attempt++)
  {
    sock_t s = tcp_connect(host, port, 5000);
    if (s == INVALID_SOCK) return NULL;

    char req[768];
    int n = snprintf(req, sizeof(req),
                     "GET %s HTTP/1.1\r\n"
                     "Host: %s\r\n"
                     "User-Agent: e_server-ref/1.0\r\n"
                     "Accept: */*\r\n"
                     "Connection: close\r\n"
                     "\r\n",
                     path, host);
    send_all(s, req, (size_t)n);

    char *resp = read_all(s);
    XCLOSE(s);
    if (!resp) return NULL;

    int code = 0;
    const char *sp = strchr(resp, ' ');
    if (sp) code = atoi(sp + 1);

    if (code >= 300 && code < 400)
    {
      char locbuf[768];
      int has_loc = 0;
      const char *loc = strstr(resp, "Location:");
      if (loc && !redirected)
      {
        loc += 9;
        while (*loc == ' ') loc++;
        if (strncmp(loc, "http://", 7) == 0)
        {
          snprintf(locbuf, sizeof(locbuf), "%s", loc);
          has_loc = 1;
        }
      }
      free(resp);
      if (!has_loc) return NULL;

      const char *l = locbuf + 7;              /* skip "http://" */
      const char *slash = strchr(l, '/');
      size_t hl = slash ? (size_t)(slash - l) : strlen(l);
      if (hl >= sizeof(nh)) return NULL;
      memcpy(nh, l, hl); nh[hl] = 0;
      if (slash) snprintf(np, sizeof(np), "%s", slash); else snprintf(np, sizeof(np), "/");
      const char *colon = strchr(nh, ':');
      if (colon) { *((char *)colon) = 0; port = atoi(colon + 1); }
      host = nh;
      path = np;
      redirected = 1;
      continue;
    }
    if (code != 200) { free(resp); return NULL; }

    const char *hdr = strstr(resp, "\r\n\r\n");
    if (!hdr) { free(resp); return NULL; }
    char *body = xstrdup(hdr + 4);
    free(resp);
    return body;
  }
  return NULL;
}

/* Extract a JSON string field: {"key":"value"}. Returns 1 if found. */
static int json_str_field(const char *body, const char *key, char *out, size_t n)
{
  char pat[96];
  snprintf(pat, sizeof(pat), "\"%s\":\"", key);
  const char *p = strstr(body, pat);
  if (!p) { out[0] = 0; return 0; }
  p += strlen(pat);
  size_t i = 0;
  while (*p && *p != '"' && i + 1 < n) out[i++] = *p++;
  out[i] = 0;
  return i > 0;
}

/* Extract a JSON numeric field (may be quoted): {"key":12.3}. */
static int json_num_field(const char *body, const char *key, char *out, size_t n)
{
  char pat[96];
  snprintf(pat, sizeof(pat), "\"%s\"", key);
  const char *p = strstr(body, pat);
  if (!p) { out[0] = 0; return 0; }
  p = strchr(p, ':');
  if (!p) { out[0] = 0; return 0; }
  p++;
  while (*p == ' ' || *p == '\t') p++;
  if (*p == '"') p++;
  size_t i = 0;
  while ((*p >= '0' && *p <= '9') || *p == '.' || *p == '-' || *p == '+')
  {
    if (i + 1 < n) out[i++] = *p;
    p++;
  }
  out[i] = 0;
  return i > 0;
}

/* --------------------------------------------------------------------------
 * Application state + API handlers
 * ------------------------------------------------------------------------ */
static int leds[3];

static void send_response(sock_t fd, int code, const char *status,
                          const char *ctype, const char *encoding,
                          const void *body, size_t len);

static void api_leds(sock_t fd, const char *method, const char *body)
{
  if (strcmp(method, "POST") == 0 && body)
  {
    const char *b = strchr(body, '[');
    if (b)
    {
      int a[3] = { 0, 0, 0 };
      int got = sscanf(b + 1, "%d , %d , %d", &a[0], &a[1], &a[2]);
      if (got > 0)
        for (int i = 0; i < got && i < 3; i++) leds[i] = a[i] ? 1 : 0;
    }
  }

  char resp[64];
  int n = snprintf(resp, sizeof(resp), "{\"leds\":[%d,%d,%d]}",
                   leds[0], leds[1], leds[2]);
  send_response(fd, 200, "OK", "application/json", NULL, resp, (size_t)n);
}

/* Simulated ADC channels, shaped like the real board (VREFINT / TEMP / VBAT).
 * On the board these would be read from the internal ADC1 channels. */
static void api_adc(sock_t fd)
{
  double t = (double)time(NULL);
  double vref = 3300.0 + 15.0 * sin(t / 4.0);
  double temp = 45.0 + 4.0 * sin(t / 3.0);
  double vbat = 3.30 + 0.02 * sin(t / 6.0);

  char resp[192];
  int n = snprintf(resp, sizeof(resp),
                   "{\"vrefint_mv\":%.1f,\"temp_c\":%.1f,\"vbat_v\":%.2f,\"ts\":%lld}",
                   vref, temp, vbat, (long long)time(NULL));
  send_response(fd, 200, "OK", "application/json", NULL, resp, (size_t)n);
}

static void get_local_ip(sock_t fd, char *out, size_t n)
{
  struct sockaddr_in sa;
#if defined(_WIN32)
  int sl = sizeof(sa);
#else
  socklen_t sl = sizeof(sa);
#endif
  if (getsockname(fd, (struct sockaddr *)&sa, &sl) == 0 && sa.sin_family == AF_INET)
    inet_ntop(AF_INET, &sa.sin_addr, out, (socklen_t)n);
  else
    snprintf(out, n, "0.0.0.0");
}

static void api_info(sock_t fd)
{
  char arch[24];
#if defined(__aarch64__) || defined(_M_ARM64)
  snprintf(arch, sizeof(arch), "aarch64");
#elif defined(__x86_64__) || defined(_M_X64)
  snprintf(arch, sizeof(arch), "x86_64");
#elif defined(__i386__) || defined(_M_IX86)
  snprintf(arch, sizeof(arch), "x86");
#elif defined(__arm__) || defined(_M_ARM)
  snprintf(arch, sizeof(arch), "arm");
#else
  snprintf(arch, sizeof(arch), "unknown");
#endif

  char lan[64] = "0.0.0.0";
  get_local_ip(fd, lan, sizeof(lan));

  /* Best-effort external lookups; any failure -> null -> "N/A" in the page. */
  char *pub = http_get("api.ipify.org", 80, "/");
  char *geo = http_get("ip-api.com", 80, "/json/");
  char *wtr = http_get("wttr.in", 80, "/?format=j1");

  char pub_ip[64] = "";
  if (pub)
  {
    char *p = pub;
    while (*p == ' ' || *p == '\t' || *p == '\r' || *p == '\n') p++;
    char *q = p + strlen(p);
    while (q > p && (q[-1] == '\r' || q[-1] == '\n' || q[-1] == ' ')) *--q = 0;
    snprintf(pub_ip, sizeof(pub_ip), "%s", p);
  }

  char city[64] = "", country[64] = "";
  if (geo)
  {
    json_str_field(geo, "city", city, sizeof(city));
    json_str_field(geo, "country", country, sizeof(country));
  }

  char wtemp[16] = "", wdesc[96] = "";
  if (wtr)
  {
    json_num_field(wtr, "temp_C", wtemp, sizeof(wtemp));
    const char *wd = strstr(wtr, "weatherDesc");
    if (wd)
    {
      const char *val = strstr(wd, "\"value\"");
      if (val)
      {
        const char *c = strchr(val, ':');
        if (c)
        {
          c++;
          while (*c == ' ' || *c == '\t') c++;
          if (*c == '"') c++;
          size_t i = 0;
          while (*c && *c != '"' && i + 1 < sizeof(wdesc)) wdesc[i++] = *c++;
          wdesc[i] = 0;
        }
      }
    }
  }

  char geo_buf[192], wtr_buf[192], resp[1024];
  char *geo_part, *wtr_part;

  if (city[0] || country[0])
  {
    snprintf(geo_buf, sizeof(geo_buf), "{\"city\":\"%s\",\"country\":\"%s\"}", city, country);
    geo_part = geo_buf;
  }
  else
  {
    geo_part = "null";
  }

  if (wtemp[0])
  {
    if (wdesc[0])
      snprintf(wtr_buf, sizeof(wtr_buf), "{\"temp_c\":%s,\"desc\":\"%s\"}", wtemp, wdesc);
    else
      snprintf(wtr_buf, sizeof(wtr_buf), "{\"temp_c\":%s}", wtemp);
    wtr_part = wtr_buf;
  }
  else
  {
    wtr_part = "null";
  }

  int n = snprintf(resp, sizeof(resp),
                   "{\"arch\":\"%s\",\"lan_ip\":\"%s\",\"public_ip\":%s%s%s,\"geo\":%s,\"weather\":%s,\"ts\":%lld}",
                   arch, lan,
                   pub_ip[0] ? "\"" : "null",
                   pub_ip[0] ? pub_ip : "",
                   pub_ip[0] ? "\"" : "",
                   geo_part, wtr_part, (long long)time(NULL));
  send_response(fd, 200, "OK", "application/json", NULL, resp, (size_t)n);

  free(pub);
  free(geo);
  free(wtr);
}

/* --------------------------------------------------------------------------
 * HTTP response plumbing + routing
 * ------------------------------------------------------------------------ */
static void send_response(sock_t fd, int code, const char *status,
                          const char *ctype, const char *encoding,
                          const void *body, size_t len)
{
  char hdr[512];
  int n = snprintf(hdr, sizeof(hdr),
                   "HTTP/1.1 %d %s\r\n"
                   "Content-Type: %s\r\n"
                   "%s"                        /* optional Content-Encoding */
                   "Content-Length: %zu\r\n"
                   "Cache-Control: no-store\r\n"
                   "Connection: close\r\n"
                   "\r\n",
                   code, status, ctype,
                   encoding ? encoding : "",
                   len);
  send_all(fd, hdr, (size_t)n);
  if (len) send_all(fd, body, len);
}

static void serve_public(sock_t fd, const char *path)
{
  for (unsigned i = 0; i < embedded_files_count; i++)
  {
    if (strcmp(path, embedded_files[i].path) == 0)
    {
      send_response(fd, 200, "OK", embedded_files[i].ctype, NULL,
                    embedded_files[i].data, embedded_files[i].len);
      return;
    }
  }
  send_response(fd, 404, "Not Found", "text/plain", NULL, "not found", 9);
}

static void route(sock_t fd, const char *method, const char *path, const char *body)
{
  if (strcmp(path, "/") == 0 || strcmp(path, "/index.html") == 0)
  {
    send_response(fd, 200, "OK", "text/html; charset=utf-8",
                  "Content-Encoding: gzip\r\n",
                  index_html_gz, index_html_gz_len);
  }
  else if (strcmp(path, "/api/leds") == 0)
  {
    api_leds(fd, method, body);
  }
  else if (strcmp(path, "/api/adc") == 0)
  {
    api_adc(fd);
  }
  else if (strcmp(path, "/api/info") == 0)
  {
    api_info(fd);
  }
  else if (strcmp(path, "/favicon.ico") == 0)
  {
    send_response(fd, 204, "No Content", "text/plain", NULL, NULL, 0);
  }
  else if (strncmp(path, "/public/", 8) == 0)
  {
    serve_public(fd, path);
  }
  else
  {
    send_response(fd, 404, "Not Found", "text/plain", NULL, "not found", 9);
  }
}

/* Read one request (headers + body) into buf. Sets *body to the start of the
 * request body (may be NULL). Returns 1 on success. */
static int read_request(sock_t fd, char *buf, size_t cap, char **body_out)
{
  size_t got = 0;
  char *body = NULL;
  *body_out = NULL;
  while (got < cap - 1)
  {
    int r = recv(fd, buf + got, (int)(cap - 1 - got), 0);
    if (r <= 0) break;
    got += (size_t)r;
    buf[got] = 0;

    char *hdr_end = strstr(buf, "\r\n\r\n");
    if (!hdr_end) continue;

    long cl = 0;
    const char *clh = strstr(buf, "Content-Length:");
    if (clh)
    {
      clh += 15;
      while (*clh == ' ') clh++;
      cl = atol(clh);
    }
    size_t want = (size_t)(hdr_end - buf) + 4 + (size_t)cl;
    if (want >= cap) return 0;
    while (got < want)
    {
      r = recv(fd, buf + got, (int)(want - got), 0);
      if (r <= 0) break;
      got += (size_t)r;
    }
    buf[got] = 0;
    if (got >= want && cl > 0) body = hdr_end + 4;
    *body_out = body;
    return got >= want;
  }
  return 0;
}

#if defined(_WIN32)
static unsigned __stdcall worker_thread(void *arg)
#else
static void *worker_thread(void *arg)
#endif
{
  sock_t fd = (sock_t)(intptr_t)arg;
  char buf[16384];
  char *body = NULL;

  if (read_request(fd, buf, sizeof(buf), &body))
  {
    char method[8] = { 0 }, path[1024] = { 0 }, ver[16] = { 0 };
    if (sscanf(buf, "%7s %1023s %15s", method, path, ver) == 3)
    {
      char *q = strchr(path, '?');
      if (q) *q = 0;
      route(fd, method, path, body);
    }
  }
  XCLOSE(fd);
#if defined(_WIN32)
  return 0;
#else
  return NULL;
#endif
}

static void start_worker(sock_t fd)
{
#if defined(_WIN32)
  HANDLE h = (HANDLE)_beginthreadex(NULL, 0, worker_thread, (void *)(intptr_t)fd, 0, NULL);
  if (h) CloseHandle(h); else XCLOSE(fd);
#else
  pthread_t t;
  if (pthread_create(&t, NULL, worker_thread, (void *)(intptr_t)fd) != 0)
    XCLOSE(fd);
  else
    pthread_detach(t);
#endif
}

int main(int argc, char **argv)
{
  int port = argc > 1 ? atoi(argv[1]) : 8080;
  sock_t srv;

  sock_init();

  srv = socket(AF_INET, SOCK_STREAM, 0);
  if (srv == INVALID_SOCK) { perror("socket"); return 1; }

  {
    int one = 1;
    setsockopt(srv, SOL_SOCKET, SO_REUSEADDR, (const char *)&one, sizeof(one));
  }

  struct sockaddr_in addr;
  memset(&addr, 0, sizeof(addr));
  addr.sin_family = AF_INET;
  addr.sin_addr.s_addr = INADDR_ANY;
  addr.sin_port = htons((unsigned short)port);

  if (bind(srv, (struct sockaddr *)&addr, sizeof(addr)) != 0) { perror("bind"); return 1; }
  if (listen(srv, 16) != 0) { perror("listen"); return 1; }

  printf("e_server reference backend: http://localhost:%d/\n", port);
  printf("  page: %u bytes gzip (index_html_gz), %u embedded public files\n",
         (unsigned)index_html_gz_len, (unsigned)embedded_files_count);
  printf("  GET /api/leds | POST /api/leds | GET /api/adc | GET /api/info\n");
  printf("  (Ctrl-C to stop)\n");

  for (;;)
  {
    sock_t c = accept(srv, NULL, NULL);
    if (c != INVALID_SOCK) start_worker(c);
  }
}
