#!/usr/bin/env python3
"""Bundle the e_server web frontend into C arrays for the (embedded) backend.

Pipeline (one command, no runtime deps beyond Python):

    [ web/index.html ] --+--> inline <style>+<script> --> index.html
    [ web/style.css  ] --+
    [ web/app.js     ] --+

    index.html -> gzip -> index_html_gz[]          (served with Content-Encoding: gzip)
    public/*      -> raw byte arrays + lookup table (images are already compressed)

Output: web_assets.h  (const uint8_t arrays + embedded_files[] table + lengths).
"""
import gzip
import os

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.join(HERE, "web")
PUBLIC = os.path.join(HERE, "public")
OUT = os.path.join(HERE, "web_assets.h")

CTYPES = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".gif": "image/gif",
    ".svg": "image/svg+xml",
}


def c_array(name, data, per_line=12):
    lines = []
    for i in range(0, len(data), per_line):
        lines.append("  " + ", ".join("0x%02x" % b for b in data[i:i + per_line]) + ",")
    return "const uint8_t %s[] = {\n%s\n};" % (name, "\n".join(lines))


def var_name(path):
    """/public/board_0_little.jpg -> public_board_0_little_jpg"""
    return path.replace("/", "_").replace(".", "_").strip("_")


def main():
    html = open(os.path.join(WEB, "index.html"), encoding="utf-8").read()
    css = open(os.path.join(WEB, "style.css"), encoding="utf-8").read()
    js = open(os.path.join(WEB, "app.js"), encoding="utf-8").read()

    html = html.replace(
        '<link rel="stylesheet" href="style.css">',
        "<style>\n" + css + "\n</style>",
    )
    html = html.replace('<script src="app.js"></script>', "<script>\n" + js + "\n</script>")

    raw = html.encode("utf-8")
    gz = gzip.compress(raw, compresslevel=9, mtime=0)

    images = []
    for fname in sorted(os.listdir(PUBLIC)):
        path = os.path.join(PUBLIC, fname)
        if not os.path.isfile(path):
            continue
        ext = os.path.splitext(fname)[1].lower()
        images.append({
            "path": "/public/" + fname,
            "ctype": CTYPES.get(ext, "application/octet-stream"),
            "var": var_name(fname),
            "data": open(path, "rb").read(),
        })

    out = []
    out.append("/* Generated by build_web.py - DO NOT EDIT. */")
    out.append("#ifndef WEB_ASSETS_H")
    out.append("#define WEB_ASSETS_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("#include <stddef.h>")
    out.append("")
    out.append("/* Single-page app: CSS+JS inlined into index.html, gzip-compressed. */")
    out.append(c_array("index_html_gz", gz))
    out.append("#define index_html_gz_len (sizeof(index_html_gz))")
    out.append("")
    if images:
        out.append("/* Public files (raw - JPEG/PNG are already compressed). */")
        for img in images:
            out.append(c_array(img["var"], img["data"]))
        out.append("")
        out.append("typedef struct {")
        out.append("  const char *path;      /* URL path, e.g. \"/public/foo.jpg\" */")
        out.append("  const char *ctype;     /* Content-Type */")
        out.append("  const uint8_t *data;")
        out.append("  uint32_t len;")
        out.append("} embedded_file_t;")
        out.append("")
        out.append("const embedded_file_t embedded_files[] = {")
        for img in images:
            out.append('  { "%s", "%s", %s, sizeof(%s) },' % (
                img["path"], img["ctype"], img["var"], img["var"]))
        out.append("};")
        out.append("#define embedded_files_count (sizeof(embedded_files) / sizeof(embedded_files[0]))")
        out.append("")
    out.append("#endif /* WEB_ASSETS_H */")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")

    print("wrote %s" % OUT)
    print("  page: %d bytes raw -> %d bytes gzip (%.1f%% of original)"
          % (len(raw), len(gz), 100.0 * len(gz) / len(raw)))
    for img in images:
        print("  %-34s %6d bytes raw" % (img["path"], len(img["data"])))


if __name__ == "__main__":
    main()
